version: '3'

services:
  docker-agent:
    image: docker:dind
    depends_on: 
      - jenkins-bo
    restart: unless-stopped
    privileged: true
    command: --storage-driver=overlay2
    networks: 
      jenkins:
        aliases: 
          - docker
    environment: 
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./vols/jenkins-docker-certs:/certs/client
      - ./vols/jenkins-data:/var/jenkins_home
    ports:
      - '2376:2376'

  jenkins-bo:
    image: jenkins-blueocean
    build:
      context: ./jenkins-bo
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes: 
      - ./vols/jenkins-data:/var/jenkins_home
      - ./vols/jenkins-docker-certs:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # - ${HOST_DEV_HOME}:/var/dev_home:ro
    networks: 
      - jenkins

networks:
  jenkins:
