jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

  securityRealm:
    local:
    # https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/embedded-userdatabase
      allowsSignup: "false"
      users:
        - id: "ladmin"
          password: "localoca"
          name: "Local Admin"
          properties:
            - mailer:
                emailAddress: "admin@jenkins.local"
  
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  
  remotingSecurity:
    enabled: true

tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git

  jdk:
    installations:
      - name: jdk8
        home: "/jdk"
        properties:
          - installSource:
              installers:
                - jdkInstaller:
                    id: "jdk-8u181-oth-JPR"
                    acceptLicense: true

unclassified:
  location:
    adminAddress: "admin@jenkins.local"
    url: "http://127.0.0.1:8080/"

  sonarglobalconfiguration:                  # mandatory
  # https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/sonarqube
    buildWrapperEnabled: true
    installations:                           # mandatory
      - name: "LOCAL"                         # id of the SonarQube configuration - to be used in jobs
        serverUrl: "http://sonarqube:9000"
        #credentialsId: token-sonarqube       # id of the credentials containing sonar auth token (since 2.9 version)
        serverAuthenticationToken: "token"   # for retrocompatibility with versions < 2.9
        # mojoVersion: "mojoVersion"
        # additionalProperties: "blah=blah"
        # additionalAnalysisProperties: "additionalAnalysisProperties"
        triggers:
          skipScmCause: true
          skipUpstreamCause: true
          # envVar: "envVar"