jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL

tool:
  git:
    installations:
      - name: git
        home: /usr/local/bin/git

  jdk:
    installations:
      - name: jdk8
        home: "/jdk"
        properties:
          - installSource:
              installers:
                - jdkInstaller:
                    id: "jdk-8u181-oth-JPR"
                    acceptLicense: true
